### PR TITLE
Use strings for params defining Person/Country/Tag/TagClass #73

### LINKED ISSUE #73: Inconsistencies for parameter types
TagClasses are sometimes represented with their ids and sometimes with their names. While both approaches work, is this intentional? If so, we should use different names (e.g. `tagClassName` vs. `tagClassId`). If not, we should agree in a unified approach.

```
bi-read-04.yaml
11:  - name: tagClass
12-    type: 32-bit Integer

bi-read-09.yaml
12-parameters:
13:  - name: tagClass1
14-    type: 32-bit Integer
15:  - name: tagClass2
16-    type: 32-bit Integer

bi-read-16.yaml
18:  - name: tagClass
19-    type: String

bi-read-19.yaml
20:  - name: tagClass1
21-    type: 32-bit Integer
22:  - name: tagClass2
23-    type: 32-bit Integer

bi-read-20.yaml
9:  - name: tagClasses
10-    type: String[]

bi-read-24.yaml
10:  - name: tagClass
11-    type: String
```

FWIW, the substitution parameter generator always generates strings:

```
q4_param.txt
1:tagClass|country
2-MusicalArtist|Netherlands

q9_param.txt
1:tagClass1|tagClass2|threshold
2-BaseballPlayer|ChristianBishop|200

q19_param.txt
1:date|tagClass1|tagClass2
2-599634000000|MusicalArtist|OfficeHolder

q24_param.txt
1:tagClass
2-Single
```

@mkaufmann @ArnauPrat @alexaverbuch @MarcusParadies

### PR DESCRIPTION
**Pull request by szarnyasg**
Fixes #73

### CODE REVIEW

**Comment by ArnauPrat** [comment]
@szarnyasg Are these changes compliant with the driver? I am asking this because I know that the driver uses results from complex read queries to execute short queries. Could your proposed changes conflict with that?

**Comment by szarnyasg** [comment]
> I am asking this because I know that the driver uses results from complex read queries to execute short queries. Could your proposed changes conflict with that?

The changes are BI only, so they cannot conflict with complex/short queries.

**Comment by szarnyasg** [comment]
> Are these changes compliant with the driver?

There are some issues with that. Let me break it down:

* [Q4](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery4PopularCountryTopics.java#L13): `tagClass` and `country` are strings :white_check_mark: 
* [Q5](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery5TopCountryPosters.java#L14): `country` is a string :white_check_mark: 
* [Q6](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery6ActivePosters.java#L13): `tag` is a string :white_check_mark: 
* [Q7](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery7AuthoritativeUsers.java): `tag` is a string :white_check_mark: 
* [Q8](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery8RelatedTopics.java#L13): `tag` is a string :white_check_mark: 
* [Q9](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery9RelatedForums.java#L13): `tagClassA` and `tagClassB` are strings :white_check_mark: 
* [Q10](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery10TagPerson.java#L13): `tag` is a string :white_check_mark: 
* [Q11](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery11UnrelatedReplies.java#L13): `country` is a string :white_check_mark: 
* [Q15](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery15SocialNormals.java#L13): `country` is a string :white_check_mark: 
* [Q16](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery16ExpertsInSocialCircle.java#L13): `tagClass` and `country` are strings, but `person` is a long :x: 
* [Q19](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery19StrangerInteraction.java#L14): `tagClassA` and `tagClassB` are strings :white_check_mark: 
* [Q25](https://github.com/ldbc/ldbc_snb_driver/blob/a25bfccaf202121d91378e9fdd0428433c30f6bf/src/main/java/com/ldbc/driver/workloads/ldbc/snb/bi/LdbcSnbBiQuery25WeightedPaths.java#L12): `person1Id` and `person2Id` are `long`s :x:

**Comment by ArnauPrat** [comment]
@szarnyasg Person Id is the only way to uniquely identify a Person. Queries 16 and 25 are defined as working on specific persons, thus I think they must be longs.

**Comment by szarnyasg** [comment]
@ArnauPrat changes Q16 and 25 back to use longs.

**Comment by szarnyasg** [comment]
Oh my. Getting more and more conflicts. We should merge this ASAP.

**Pull request merged**
